/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Selvin Aguilar
 */
public class Battles extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Battles() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarEstadisticas();
    }
    
   private void mostrarEstadisticas() {
    int activos = UserManager.getUsuariosActivos();
    int historicos = UserManager.getUsuariosHistoricos();
    int total = BattleStats.partidasJugadas;
    int heroes = BattleStats.victoriasHeroes;
    int villanos = BattleStats.victoriasVillanos;

    String texto = "BATALLAS - ESTADÍSTICAS\n\n" +
                   "1. Usuarios Activos: " + activos + "\n" +
                   "2. Usuarios Históricos: " + historicos + "\n\n" +
                   "3. Partidas Jugadas: " + total + "\n" +
                   "   a. Victorias de HÉROES: " + heroes + "\n" +
                   "   b. Victorias de VILLANOS: " + villanos;

    jTextArea1.setText(texto);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        Title_Ranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BG_Ranking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setBackground(new java.awt.Color(153, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("REGRESAR");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 790, 210, 50));

        Title_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Battles_Ttl.png"))); // NOI18N
        getContentPane().add(Title_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 710, 300));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 600, 400));

        BG_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_Batallas.jpg"))); // NOI18N
        getContentPane().add(BG_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres volver al Universo Marvel de Stratego Marvel Heroes?",
            "Regresar a Menu", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Marvel_Universe marveluniverse =new Marvel_Universe();
            marveluniverse.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Ranking;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel Title_Ranking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
