/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import javax.swing.JOptionPane;

/**
 *
 * @author Selvin Aguilar
 */
public class Beginning extends javax.swing.JFrame {

    /**
     * Creates new form Beginning
     */
    public Beginning() {
        initComponents();
        setLocationRelativeTo(null);
        
        SignIn_Button.setContentAreaFilled(false); 
        SignIn_Button.setBorderPainted(false);    
        SignIn_Button.setFocusPainted(false);     
        SignIn_Button.setOpaque(false);
        
        SignUp_Button.setContentAreaFilled(false); 
        SignUp_Button.setBorderPainted(false);    
        SignUp_Button.setFocusPainted(false);     
        SignUp_Button.setOpaque(false);
        
        Exit_Button.setContentAreaFilled(false); 
        Exit_Button.setBorderPainted(false);    
        Exit_Button.setFocusPainted(false);     
        Exit_Button.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Title_Stratego = new javax.swing.JLabel();
        SignIn_Button = new javax.swing.JButton();
        SignUp_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        BG_Beginning = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Stratego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Stratego_big.png"))); // NOI18N
        getContentPane().add(Title_Stratego, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        SignIn_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignIn.png"))); // NOI18N
        SignIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignIn_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 350, 170));

        SignUp_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignUp.png"))); // NOI18N
        SignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 380, 170));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 350, 170));

        BG_Beginning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_Beginning.jpg"))); // NOI18N
        getContentPane().add(BG_Beginning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ButtonActionPerformed
        NewUser newuser = new NewUser();
        newuser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUp_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres salir de Stratego Marvel Heroes?", 
                    "Confirmar salida", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void SignIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignIn_ButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignIn_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beginning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Beginning;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton SignIn_Button;
    private javax.swing.JButton SignUp_Button;
    private javax.swing.JLabel Title_Stratego;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
