/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyecto2copia.Game;

/**
 *
 * @author Selvin Aguilar
 */

public class First_Page extends javax.swing.JFrame {

    private static String jugadorActual = null;

    public static void setJugadorActual(String User) {
        jugadorActual = User;
    }

    public static String getJugadorActual() {
        return jugadorActual;
    }
    

    /**
     * Creates new form First_Page
     */
    public First_Page() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public First_Page(String nombreUsuario) {
        initComponents();
        this.jugadorActual = jugadorActual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Stratego = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        NewMatch_Button = new javax.swing.JButton();
        MarvelUniverse_Button = new javax.swing.JButton();
        BG_FirstPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Stratego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Stratego_medium.png"))); // NOI18N
        getContentPane().add(Title_Stratego, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -40, 720, 380));

        Exit_Button.setBackground(new java.awt.Color(153, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("CERRAR SESIÓN");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 753, 210, 50));

        Profile_Button.setBackground(new java.awt.Color(204, 0, 0));
        Profile_Button.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        Profile_Button.setForeground(new java.awt.Color(255, 255, 255));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyProfile_Bttn.png"))); // NOI18N
        Profile_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        Profile_Button.setOpaque(true);
        Profile_Button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Profile_ButtonMouseMoved(evt);
            }
        });
        Profile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 370, 140));

        NewMatch_Button.setBackground(new java.awt.Color(255, 255, 255));
        NewMatch_Button.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        NewMatch_Button.setForeground(new java.awt.Color(255, 255, 255));
        NewMatch_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewMatch_Bttn.png"))); // NOI18N
        NewMatch_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        NewMatch_Button.setOpaque(true);
        NewMatch_Button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                NewMatch_ButtonMouseMoved(evt);
            }
        });
        NewMatch_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMatch_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewMatch_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 370, 140));

        MarvelUniverse_Button.setBackground(new java.awt.Color(204, 0, 0));
        MarvelUniverse_Button.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        MarvelUniverse_Button.setForeground(new java.awt.Color(255, 255, 255));
        MarvelUniverse_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MarvelUniverse_Bttn.png"))); // NOI18N
        MarvelUniverse_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        MarvelUniverse_Button.setOpaque(true);
        MarvelUniverse_Button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MarvelUniverse_ButtonMouseMoved(evt);
            }
        });
        MarvelUniverse_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarvelUniverse_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MarvelUniverse_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 370, 140));

        BG_FirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_FirstPage.jpg"))); // NOI18N
        getContentPane().add(BG_FirstPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1310, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres cerrar sesión en Stratego Marvel Heroes?",
                "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            First_Page.setJugadorActual(null);
            Beginning beginning = new Beginning();
            beginning.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        MyProfile myProfile = new MyProfile();
        myProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Profile_ButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_ButtonMouseMoved

    }//GEN-LAST:event_Profile_ButtonMouseMoved

    private void NewMatch_ButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMatch_ButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMatch_ButtonMouseMoved

    private void NewMatch_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMatch_ButtonActionPerformed
       if (MyProfile.getJugadorActual() == null) {
        JOptionPane.showMessageDialog(null, "Debes iniciar sesión para jugar.");
        return;
    }

    ArrayList<User> usuarios = UserManager.getUsuarios();

    ArrayList<String> nombresDisponibles = new ArrayList<>();
    for (User u : usuarios) {
        if (!u.getNombre().trim().equalsIgnoreCase(jugadorActual.trim())) {
            nombresDisponibles.add(u.getNombre());
        }
    }

    if (nombresDisponibles.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No hay otros usuarios registrados para jugar contra.");
        return;
    }

    // Selección de oponente
    String[] nombres = nombresDisponibles.toArray(new String[0]);
    String oponenteSeleccionado = (String) JOptionPane.showInputDialog(
            null,
            "Selecciona un oponente:",
            "Elegir Oponente",
            JOptionPane.PLAIN_MESSAGE,
            null,
            nombres,
            nombres[0]
    );

    if (oponenteSeleccionado == null) {
        JOptionPane.showMessageDialog(null, "No se seleccionó ningún usuario.");
        return;
    }

    // Mostrar la selección final
    JOptionPane.showMessageDialog(null,
            "Has seleccionado al oponente: " + oponenteSeleccionado);
    Game.setOponente(oponenteSeleccionado);
    
    Game game = new Game();
        game.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_NewMatch_ButtonActionPerformed

    private void MarvelUniverse_ButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarvelUniverse_ButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MarvelUniverse_ButtonMouseMoved

    private void MarvelUniverse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarvelUniverse_ButtonActionPerformed
        Marvel_Universe marvelUniverse = new Marvel_Universe();
        marvelUniverse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MarvelUniverse_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_FirstPage;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton MarvelUniverse_Button;
    private javax.swing.JButton NewMatch_Button;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JLabel Title_Stratego;
    // End of variables declaration//GEN-END:variables
}
