/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import javax.swing.JOptionPane;
import proyecto2copia.Game;

/**
 *
 * @author Selvin Aguilar
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        SignIn_Button.setContentAreaFilled(false); 
        SignIn_Button.setBorderPainted(false);    
        SignIn_Button.setFocusPainted(false);     
        SignIn_Button.setOpaque(false);
        
        Exit_Button.setContentAreaFilled(false); 
        Exit_Button.setBorderPainted(false);    
        Exit_Button.setFocusPainted(false);     
        Exit_Button.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Stratego = new javax.swing.JLabel();
        Title_SignIn = new javax.swing.JLabel();
        User_text = new javax.swing.JLabel();
        User_TextField = new javax.swing.JTextField();
        Password_text = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        SignIn_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        BG_SignIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Stratego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Stratego_small.png"))); // NOI18N
        getContentPane().add(Title_Stratego, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 360, 150));

        Title_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignIn_Ttl.png"))); // NOI18N
        getContentPane().add(Title_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 380, 200));

        User_text.setBackground(new java.awt.Color(255, 204, 51));
        User_text.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        User_text.setForeground(new java.awt.Color(255, 255, 255));
        User_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_text.setText("USUARIO:");
        User_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        User_text.setOpaque(true);
        getContentPane().add(User_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 290, 60));

        User_TextField.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        User_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(User_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 330, 60));

        Password_text.setBackground(new java.awt.Color(255, 204, 0));
        Password_text.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        Password_text.setForeground(new java.awt.Color(255, 255, 255));
        Password_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password_text.setText("CONTRASEÑA:");
        Password_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Password_text.setOpaque(true);
        getContentPane().add(Password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 410, 60));

        Password_Field.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        Password_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 330, 60));

        SignIn_Button.setBackground(new java.awt.Color(153, 153, 153));
        SignIn_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        SignIn_Button.setForeground(new java.awt.Color(255, 255, 255));
        SignIn_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignIn.png"))); // NOI18N
        SignIn_Button.setText("INICIAR SESION");
        SignIn_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignIn_ButtonMouseClicked(evt);
            }
        });
        SignIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignIn_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 370, 160));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit_im.png"))); // NOI18N
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 690, 180, 80));

        BG_SignIn.setForeground(new java.awt.Color(0, 0, 0));
        BG_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_InUp.jpg"))); // NOI18N
        getContentPane().add(BG_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_TextFieldActionPerformed

    private void SignIn_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_ButtonMouseClicked

    private void SignIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignIn_ButtonActionPerformed
        String User_name = User_TextField.getText().trim();
        String password_user = new String(Password_Field.getPassword()).trim();
        

    if (UserManager.verificarUsuario(User_name, password_user)) {
        First_Page.setJugadorActual(User_name);
        Game.setJugadorActual(User_name);
        MyProfile.setJugadorActual(User_name);

        JOptionPane.showMessageDialog(this, "El Usuario " + User_name + " ha iniciado sesión.");

        First_Page firstPage = new First_Page(User_name);
        firstPage.setVisible(true);

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta. Intente de nuevo!");
    }
    }//GEN-LAST:event_SignIn_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres regresar a pantalla de Inicio de Stratego Marvel Heroes?",
            "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            First_Page.setJugadorActual(null);
            Beginning beginning =new Beginning();
            beginning.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_SignIn;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_text;
    private javax.swing.JButton SignIn_Button;
    private javax.swing.JLabel Title_SignIn;
    private javax.swing.JLabel Title_Stratego;
    private javax.swing.JTextField User_TextField;
    private javax.swing.JLabel User_text;
    // End of variables declaration//GEN-END:variables
}
