/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import javax.swing.JOptionPane;

/**
 *
 * @author Selvin Aguilar
 */
public class Marvel_Universe extends javax.swing.JFrame {

    /**
     * Creates new form Marvel_Universe
     */
    public Marvel_Universe() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Universe = new javax.swing.JLabel();
        Battles_Button = new javax.swing.JButton();
        Ranking_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        BG_MarvelUniverse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Universe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MarvelUniverse_Ttl.png"))); // NOI18N
        getContentPane().add(Title_Universe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 320));

        Battles_Button.setBackground(new java.awt.Color(204, 0, 0));
        Battles_Button.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        Battles_Button.setForeground(new java.awt.Color(255, 255, 255));
        Battles_Button.setText("BATALLAS");
        Battles_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        Battles_Button.setOpaque(true);
        Battles_Button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Battles_ButtonMouseMoved(evt);
            }
        });
        Battles_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Battles_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Battles_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 360, 90));

        Ranking_Button.setBackground(new java.awt.Color(255, 255, 255));
        Ranking_Button.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        Ranking_Button.setForeground(new java.awt.Color(204, 0, 0));
        Ranking_Button.setText("RANKING");
        Ranking_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        Ranking_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ranking_Button.setOpaque(true);
        Ranking_Button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Ranking_ButtonMouseMoved(evt);
            }
        });
        Ranking_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ranking_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Ranking_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 360, 90));

        Exit_Button.setBackground(new java.awt.Color(153, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("REGRESAR");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 760, 210, 50));

        BG_MarvelUniverse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_UniversoMarvel.jpg"))); // NOI18N
        getContentPane().add(BG_MarvelUniverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Battles_ButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Battles_ButtonMouseMoved

    }//GEN-LAST:event_Battles_ButtonMouseMoved

    private void Battles_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Battles_ButtonActionPerformed
            Battles battles =new Battles();
            battles.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_Battles_ButtonActionPerformed

    private void Ranking_ButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ranking_ButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Ranking_ButtonMouseMoved

    private void Ranking_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ranking_ButtonActionPerformed
            Ranking ranking =new Ranking();
            ranking.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_Ranking_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres volver al Menu de Stratego Marvel Heroes?",
            "Regresar a Menu", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            First_Page firstPage =new First_Page();
            firstPage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marvel_Universe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marvel_Universe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marvel_Universe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marvel_Universe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marvel_Universe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_MarvelUniverse;
    private javax.swing.JButton Battles_Button;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Ranking_Button;
    private javax.swing.JLabel Title_Universe;
    // End of variables declaration//GEN-END:variables
}
