/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import aguilar_robert_strategomarvelheroes.First_Page;
import aguilar_robert_strategomarvelheroes.User;
import aguilar_robert_strategomarvelheroes.UserManager;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Selvin Aguilar
 */
public class MyProfile extends javax.swing.JFrame {
private static String jugadorActual = null;

public static void setJugadorActual(String User) {
    jugadorActual = User;
}

public static String getJugadorActual() {
    return jugadorActual;
}
    /**
     * Creates new form MyProfile
     */
    public MyProfile() {
        initComponents();
        mostrarPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DeleteActualUser_Button = new javax.swing.JButton();
        ChangePassword_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BG_MyProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyProfile_Ttl.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 720, 330));

        DeleteActualUser_Button.setBackground(new java.awt.Color(0, 0, 0));
        DeleteActualUser_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        DeleteActualUser_Button.setForeground(new java.awt.Color(255, 255, 255));
        DeleteActualUser_Button.setText("ELIMINAR CUENTA");
        DeleteActualUser_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActualUser_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteActualUser_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 290, 50));

        ChangePassword_Button.setBackground(new java.awt.Color(0, 0, 0));
        ChangePassword_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ChangePassword_Button.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassword_Button.setText("CAMBIAR CONTRASEÑA");
        ChangePassword_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassword_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ChangePassword_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 290, 50));

        Exit_Button.setBackground(new java.awt.Color(153, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("REGRESAR");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 210, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 600, 250));

        BG_MyProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_MyProfile.png"))); // NOI18N
        getContentPane().add(BG_MyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres volver al Menú de Stratego Marvel Heroes?",
            "Regresar a Menu", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            First_Page firstPage =new First_Page();
            firstPage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void ChangePassword_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassword_ButtonActionPerformed
       UserManager.cambiarContrasenaJugadorActual();
    }//GEN-LAST:event_ChangePassword_ButtonActionPerformed

    private void DeleteActualUser_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActualUser_ButtonActionPerformed
        UserManager.eliminarJugadorActual();
        this.dispose();
    }//GEN-LAST:event_DeleteActualUser_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void mostrarPerfil() {
    String nombreUsuario = getJugadorActual(); // nombre actual del jugador

    for (User u : UserManager.getUsuarios()) {
        if (u.getNombre().equalsIgnoreCase(nombreUsuario)) {
            StringBuilder info = new StringBuilder();
            info.append("Nombre de Usuario: ").append(u.getNombre()).append("\n")
                .append("Puntos: ").append(u.getPuntos()).append("\n\n");

            info.append("Últimos Partidos:\n");

            List<LogMatchs> logsUsuario = UserManager.obtenerLogsDeUsuario(nombreUsuario);
            if (logsUsuario.isEmpty()) {
                info.append("No hay registros de partidas aún.");
            } else {
                for (LogMatchs log : logsUsuario) {
                    info.append(log.toString());
                }
            }

            jTextArea1.setText(info.toString());
            return;
        }
    }

    jTextArea1.setText("No se encontró el perfil del jugador.");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_MyProfile;
    private javax.swing.JButton ChangePassword_Button;
    private javax.swing.JButton DeleteActualUser_Button;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
