/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import javax.swing.JOptionPane;
import proyecto2copia.Game;

/**
 *
 * @author Selvin Aguilar
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        setLocationRelativeTo(null);
        
        SignUp_Button.setContentAreaFilled(false); 
        SignUp_Button.setBorderPainted(false);    
        SignUp_Button.setFocusPainted(false);     
        SignUp_Button.setOpaque(false);
        
        Exit_Button.setContentAreaFilled(false); 
        Exit_Button.setBorderPainted(false);    
        Exit_Button.setFocusPainted(false);     
        Exit_Button.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Stratego = new javax.swing.JLabel();
        Title_SignUp = new javax.swing.JLabel();
        User_text = new javax.swing.JLabel();
        User_TextField = new javax.swing.JTextField();
        Password_text = new javax.swing.JLabel();
        Password_TextField = new javax.swing.JTextField();
        SignUp_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        BG_SignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Stratego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Stratego_small.png"))); // NOI18N
        getContentPane().add(Title_Stratego, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        Title_SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignUp_Ttl.png"))); // NOI18N
        getContentPane().add(Title_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        User_text.setBackground(new java.awt.Color(255, 255, 255));
        User_text.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        User_text.setForeground(new java.awt.Color(0, 153, 51));
        User_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_text.setText("NOMBRE USUARIO:");
        User_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        User_text.setOpaque(true);
        getContentPane().add(User_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 560, 60));

        User_TextField.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        User_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(User_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 560, 60));

        Password_text.setBackground(new java.awt.Color(255, 255, 255));
        Password_text.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        Password_text.setForeground(new java.awt.Color(0, 153, 51));
        Password_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password_text.setText("CONTRASEÑA:");
        Password_text.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        Password_text.setOpaque(true);
        getContentPane().add(Password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 410, 60));

        Password_TextField.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 410, 60));

        SignUp_Button.setBackground(new java.awt.Color(0, 51, 153));
        SignUp_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        SignUp_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignUp.png"))); // NOI18N
        SignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 370, 160));

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit_im.png"))); // NOI18N
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 180, 80));

        BG_SignUp.setBackground(new java.awt.Color(255, 255, 255));
        BG_SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_InUp.jpg"))); // NOI18N
        getContentPane().add(BG_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void User_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_TextFieldActionPerformed

    private void SignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ButtonActionPerformed
        String nombre = User_TextField.getText().trim();
    String contrasena = Password_TextField.getText().trim();

    if (nombre.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, llena ambos campos.");
        return;
    }
    if (contrasena.length() < 5 || contrasena.length() > 5) {
        JOptionPane.showMessageDialog(this, "La contraseña debe contener 5 caracteres.");
        return;
    }
    if (UserManager.usuarioExiste(nombre)) {
        JOptionPane.showMessageDialog(this, "Nombre de usuario ya está en uso. Intenta con un nombre de usuario distinto!");
        return;
    }

    User nuevoUsuario = new User(nombre, contrasena, 0);
    UserManager.agregarUsuario(nuevoUsuario);
    Game.setJugadorActual(nombre);
    First_Page.setJugadorActual(nombre);
    
    MyProfile.setJugadorActual(nombre);

    JOptionPane.showMessageDialog(this, "¡Usuario registrado exitosamente!");

    User_TextField.setText("");
    Password_TextField.setText("");

    this.dispose();
    new First_Page().setVisible(true);

    }//GEN-LAST:event_SignUp_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres regresar a pantalla de Inicio de Stratego Marvel Heroes?",
            "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            First_Page.setJugadorActual(null);
            Beginning beginning =new Beginning();
            beginning.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_SignUp;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JLabel Password_text;
    private javax.swing.JButton SignUp_Button;
    private javax.swing.JLabel Title_SignUp;
    private javax.swing.JLabel Title_Stratego;
    private javax.swing.JTextField User_TextField;
    private javax.swing.JLabel User_text;
    // End of variables declaration//GEN-END:variables
}
