/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_robert_strategomarvelheroes;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Selvin Aguilar
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        setLocationRelativeTo(null);
        cargarRanking();
    }
    
    private void cargarRanking() {
    List<User> usuariosOrdenados = UserManager.obtenerUsuariosOrdenadosPorNombreYPuntos();
    String[] datos = new String[usuariosOrdenados.size()];

    for (int i = 0; i < usuariosOrdenados.size(); i++) {
        User u = usuariosOrdenados.get(i);
        datos[i] = (i + 1) + ". " + u.getNombre() + " - Puntos: " + u.getPuntos();
    }

    jList1.setListData(datos);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Ranking = new javax.swing.JLabel();
        RankingList_ScrollPane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Exit_Button = new javax.swing.JButton();
        BG_Ranking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RankingTtl.png"))); // NOI18N
        getContentPane().add(Title_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 710, 300));

        jList1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        RankingList_ScrollPane.setViewportView(jList1);

        getContentPane().add(RankingList_ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 400, 380));

        Exit_Button.setBackground(new java.awt.Color(153, 0, 0));
        Exit_Button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_Button.setText("REGRESAR");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 790, 210, 50));

        BG_Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG_Ranking.jpg"))); // NOI18N
        getContentPane().add(BG_Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres volver al Universo Marvel de Stratego Marvel Heroes?",
            "Regresar a Menu", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Marvel_Universe marveluniverse =new Marvel_Universe();
            marveluniverse.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Ranking;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JScrollPane RankingList_ScrollPane;
    private javax.swing.JLabel Title_Ranking;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
